blog/urls.py
from django.contrib import admin
from django.urls import path
from . import views

# Espace de nom
app_name = 'blog'

urlpatterns = [
    path('', views.BlogHome.as_view(), name='home'),
    path('create/', views.BlogPostCreate.as_view(), name='create'),
    path('update/<str:slug>/', views.BlogPostUpdate.as_view(), name='update'),
    path('<str:slug>/', views.BlogPostDetail.as_view(), name='post'),
    path('delete/<str:slug>/', views.BlogPostDelete.as_view(), name='delete'),
    path('article-<str:num_art>/', views.article, name='article'),
]

blog_django/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.home, name='home'),
    path('blog/', include('blog.urls')),
    path("admin/", admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse
from django.utils.text import slugify

# Create your models here.

User = get_user_model() # To get username from django auth..


class BlogPost(models.Model):
    title = models.CharField(max_length=255, unique=True, verbose_name='Titre')
    slug = models.SlugField(max_length=255, blank=True, unique=True)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    last_updated = models.DateTimeField(auto_now=True)
    created_on = models.DateField(blank=True, null=True)
    published = models.BooleanField(default=False, verbose_name='Publié')
    content = models.TextField(blank=True, verbose_name='Contenu')

    class Meta:
        ordering = ['-created_on']
        verbose_name = 'Article'

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    @property
    def author_or_default(self):
        return self.author.username if self.author else "auteur inconnu"

    def get_absolute_url(self):
        """
            We use this method to redirect user in blog home page
            the method need to be named that way (get_absolute_url)
        """
        return reverse('blog:home')

blog/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView

from .models import BlogPost


class BlogHome(ListView):
    model = BlogPost  # Le model à utiliser
    context_object_name = 'posts'  # Variable à utiliser dans le fichier de template (par défaut: blogpost_list)

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.request.user.is_authenticated:
            return queryset
        return queryset.filter(published=True)


@method_decorator(login_required, name='dispatch')
class BlogPostCreate(CreateView):
    model = BlogPost
    template_name = "blog/blogpost_create.html"  # On définit le template à utiliser pour la création d'article
    fields = ['title', 'content']  # On définit les champs qu'on souhaite afficher


@method_decorator(login_required, name='dispatch')
class BlogPostUpdate(UpdateView):
    model = BlogPost
    template_name = 'blog/blogpost_update.html'
    fields = ['title', 'content', 'published', ]


class BlogPostDetail(DetailView):
    model = BlogPost
    context_object_name = 'post'


class BlogPostDelete(DeleteView):
    model = BlogPost
    context_object_name = 'post'
    success_url = reverse_lazy('blog:home')  # L'url de redirection après suppression d'un article


# Create your views here.
def blog(request):
    return render(request, 'blog/blog.html')


def article(request, num_art):
    if num_art in ['01', '02', '03']:
        return render(request, f'blog/article-{num_art}.html')
    return render(request, 'blog/aticle-not-found.html')

blog_django/views.py
from django.http import HttpResponse
from django.shortcuts import render


def home(request):
    context = {
        'nom': 'KENGNI',
        'prenom': 'Hippolyte'
    }
    return render(request, 'index.html', context)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	{% block title %}<title>Accueil du site</title>{% endblock %}
	<!-- Google Font Family Link Start -->
	<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Montserrat:400,700">
	<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Open+Sans:400,700,800">
	<!-- Google Font Family Link End -->

	<!-- CSS -->
	<link href="{% static 'css/style.css' %}" rel="stylesheet">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


	<!-- Include Datatables plugin script and css -->
	<link rel="stylesheet" href="//cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css">
	<script src="//cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>

	<style>
		body, .main-section p, .mce-content-body p{
			font:Normal  14px/24px "Open Sans", sans-serif;letter-spacing: 0px;text-transform: none;color: #515151 !important;
		}
	</style>
</head>
<body>


    <!-- BEGIN LOADING HEADER HERE -->
    {% include 'includes/header.html' %}
    <!-- END LOADING HEADER -->

    <!-- BEGIN LOADING CONTENT HERE -->
    {% block content %}
        <!-- CONTENT GOES HERE -->
    {% endblock  %}
    <!-- END LOADING CONTENT -->

    <!-- BEGIN LOADING FOOTER HERE -->
    {% include 'includes/footer.html' %}
    <!-- END LOADING FOOTER -->

templates/blog/article-01.html
<h4>Article n°1</h4>

templates/blog/article-02.html
<h4>Article n°2</h4>

templates/blog/article-03.html
<h4>Article n°3</h4>

templates/blog/aticle-not-found.html
Pas d'article sous ce nom

templates/blog/blogpost_confirm_delete.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    <title>Suppression d'un article</title>
{% endblock %}

        {% block content %}
        <!-- Main Section Start -->
            <form method="POST">
                {% csrf_token %}
                <p>Etes-vous sûr de vouloir supprimer '{{ post }}'?</p> <!-- la variable form vient de la class CreateView -->
                <input type="submit" value="Oui, supprimer">
            </form>
		<!-- Main Section End -->
        {% endblock %}

templates/blog/blogpost_create.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    <title>Création d'un article</title>
{% endblock %}

        {% block content %}
        <!-- Main Section Start -->
            <h1>Ajouter un article</h1>
            <form method="POST">
                {% csrf_token %}
                {{ form }} <!-- la variable form vient de la class CreateView -->
                <input type="submit" value="Créer">
            </form>
		<!-- Main Section End -->
        {% endblock %}

templates/blog/blogpost_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    <title>{{ post.title }}</title>
{% endblock %}

        {% block content %}
        <!-- Main Section Start -->
            <article>
                <h2>{{ post.title }}</h2>
                <div>{{ post.content | linebreaks | safe }}</div>
            </article>
		<!-- Main Section End -->
        {% endblock %}

templates/blog/blogpost_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    <title>Accueil du blog</title>
{% endblock %}

        {% block content %}
        <!-- Main Section Start -->
            <h1>Le blog de test</h1>
            {% for post in posts %}
                <article>
                    <h2>{{ post.title }}</h2>
                    <div>
                        {% if request.user.is_authenticated %}
                            <a href="{% url 'blog:update' slug=post.slug %}">Editer</a>
                            <a href="{% url 'blog:delete' slug=post.slug %}">Supprimer</a>
                        {% endif %}
                    </div>
                    <h5>Publié par <i>{{ post.author_or_default }}</i> le {{ post.created_on | date:'j F Y' }}</h5>
                    <p>{{ post.content | safe | truncatewords:50 }}</p>

                    <form action="{% url 'blog:post' slug=post.slug %}">
                        <button>Lire l'article</button>
                    </form>
                </article>
            {% endfor %}
		<!-- Main Section End -->
        {% endblock %}

templates/blog/blogpost_update.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    <title>Edition d'un article</title>
{% endblock %}

        {% block content %}
        <!-- Main Section Start -->
            <h1>Modifier l'article</h1>
            <form method="POST">
                {% csrf_token %}
                {{ form }} <!-- la variable form vient de la class CreateView -->
                <input type="submit" value="Editer">
            </form>
		<!-- Main Section End -->
        {% endblock %}

templates/includes/footer.html
{% load static %}

        <!-- Footer Start -->
        <div class="container">
          <footer class="py-5">
            <div class="row">
              <div class="col-6 col-md-2 mb-3">
                <h5>Section</h5>
                <ul class="nav flex-column">
                  <li class="nav-item mb-2"><a href="{% url 'home' %}" class="nav-link p-0 text-muted">Home</a></li>
                  <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Features</a></li>
                  <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Pricing</a></li>
                  <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">FAQs</a></li>
                  <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">About</a></li>
                </ul>
              </div>

              <div class="col-6 col-md-2 mb-3">
                <h5>Section</h5>
                <ul class="nav flex-column">
                  <li class="nav-item mb-2"><a href="{% url 'home' %}" class="nav-link p-0 text-muted">Home</a></li>
                  <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Features</a></li>
                  <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Pricing</a></li>
                  <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">FAQs</a></li>
                  <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">About</a></li>
                </ul>
              </div>

              <div class="col-6 col-md-2 mb-3">
                <h5>Section</h5>
                <ul class="nav flex-column">
                  <li class="nav-item mb-2"><a href="{% url 'home' %}" class="nav-link p-0 text-muted">Home</a></li>
                  <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Features</a></li>
                  <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Pricing</a></li>
                  <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">FAQs</a></li>
                  <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">About</a></li>
                </ul>
              </div>

              <div class="col-md-5 offset-md-1 mb-3">
                <form>
                  <h5>Subscribe to our newsletter</h5>
                  <p>Monthly digest of what's new and exciting from us.</p>
                  <div class="d-flex flex-column flex-sm-row w-100 gap-2">
                    <label for="newsletter1" class="visually-hidden">Email address</label>
                    <input id="newsletter1" type="text" class="form-control" placeholder="Email address">
                    <button class="btn btn-primary" type="button">Subscribe</button>
                  </div>
                </form>
              </div>
            </div>

            <div class="d-flex flex-column flex-sm-row justify-content-between py-4 my-4 border-top">
              <p>&copy {% now 'Y' %} Django, Inc. All rights reserved.</p>
              <ul class="list-unstyled d-flex">
                <li class="ms-3"><a class="link-dark" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#twitter"></use></svg></a></li>
                <li class="ms-3"><a class="link-dark" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#instagram"></use></svg></a></li>
                <li class="ms-3"><a class="link-dark" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#facebook"></use></svg></a></li>
              </ul>
            </div>
          </footer>
        </div>
		<!-- Footer End -->
	</div>

	<!-- JAVASCRIPT -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>

</body>

</html>

templates/includes/header.html
{% load static %}
<!--Main Wrapper-->
<div class="wrapper">
    <!-- Header Start -->
    <header id="header">
        <div class="main-header">
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark" aria-label="Fifth navbar example">
                    <div class="container-fluid">
                      <a class="navbar-brand" href="{% url 'home' %}">Django blog</a>
                      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample05" aria-controls="navbarsExample05" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                      </button>

                      <div class="collapse navbar-collapse" id="navbarsExample05">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                          <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'blog:home' %}">Home</a>
                          </li>
                          <li class="nav-item">
                            {% if request.user.is_authenticated %}
                            <a class="nav-link" href="{% url 'blog:create' %}">Ajouter un article</a>
                            {% endif %}
                          </li>
                          <li class="nav-item">
                            <a class="nav-link disabled">Disabled</a>
                          </li>
                          <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown" aria-expanded="false">Dropdown</a>
                            <ul class="dropdown-menu">
                              <li><a class="dropdown-item" href="#">Action</a></li>
                              <li><a class="dropdown-item" href="#">Another action</a></li>
                              <li><a class="dropdown-item" href="#">Something else here</a></li>
                            </ul>
                          </li>
                        </ul>
                        <form role="search">
                          <input class="form-control" type="search" placeholder="Search" aria-label="Search">
                        </form>
                      </div>
                    </div>
                </nav>
        </div>
    </header>
    <!-- Header End -->

templates/index.html
{% extends 'base.html' %}
{% load static %}

        {% block content %}
        <!-- Main Section Start -->
            <h4>Page index.html</h4>
		<!-- Main Section End -->
        {% endblock %}